M48
; DRILL file {KiCad 7.0.6} date Tue Feb  6 23:20:14 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-06T23:20:14+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X129.692Y-90.018
X129.692Y-105.258
X164.59Y-105.258
X164.592Y-89.985
T0
M30
